default:
  image: node:20.9.0

#variables:
# VERCEL_TOKEN: $VERCEL_TOKEN # Define sensitive information via GitLab variables

cache:
  paths:
    - node_modules/

before_script:
  - npm install --global vercel

deploy_preview:
  stage: deploy
  except:
    - main
  script:
    - vercel pull --yes --environment=preview --token=HJfDdsLqAEhjaGEXVvvAahQz
    - vercel build --token=HJfDdsLqAEhjaGEXVvvAahQz
    - vercel deploy --prebuilt --token=HJfDdsLqAEhjaGEXVvvAahQz

deploy_production:
  stage: deploy
  only:
    - main
  script:
    - vercel pull --yes --environment=production --token=HJfDdsLqAEhjaGEXVvvAahQz
    - vercel build --prod --token=HJfDdsLqAEhjaGEXVvvAahQz
    - vercel deploy --prebuilt --prod --token=HJfDdsLqAEhjaGEXVvvAahQz
